### ISSUE TITLE
readthedocs not updated on github pushes?

### ISSUE THREAD

**Issue by marscher** [markovmodel/molPX#41]
change the docs...

**Comment by gph82** [comment]
You mean here? Where exactly? 
https://github.com/markovmodel/molPX/blob/docsfixes/doc/source/INSTALL.rst

**Comment by marscher** [comment]
https://molpx.readthedocs.io/en/latest/INSTALL.html

**Comment by marscher** [comment]
fixed that. I had to disable the execution of the example notebooks (since this would require a proper install and we can not do this on read the docs)
