### ISSUE TITLE
TraitError   

### ISSUE THREAD

**Issue by gokulalgates** [markovmodel/molPX#43]
I am trying to run the example file which is given in http://molpx.readthedocs.io/en/stable/Projection_Explorer_Copy.html I am getting following error 

 
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
~/miniconda3/lib/python3.6/site-packages/traitlets/traitlets.py in validate_elements(self, obj, value)
   2251             try:
-> 2252                 v = self._trait._validate(obj, v)
   2253             except TraitError:

~/miniconda3/lib/python3.6/site-packages/traitlets/traitlets.py in _validate(self, obj, value)
    590         if hasattr(self, 'validate'):
--> 591             value = self.validate(obj, value)
    592         if obj._cross_validation_lock is False:

~/miniconda3/lib/python3.6/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   1676         else:
-> 1677             self.error(obj, value)
   1678 

~/miniconda3/lib/python3.6/site-packages/traitlets/traitlets.py in error(self, obj, value)
   1523 
-> 1524         raise TraitError(e)
   1525 

TraitError: The 'None' trait of a MolPXHBox instance must be a Widget, but a value of class 'matplotlib.backends.backend_agg.FigureCanvasAgg' (i.e. <matplotlib.backends.backend_agg.FigureCanvasAgg object at 0x7fddb7133898>) was specified.

During handling of the above exception, another exception occurred:

TraitError                                Traceback (most recent call last)
<ipython-input-7-d64f9c5dd3c4> in <module>()
      6                                                       #Y,
      7                                                       nbins=50,
----> 8                                                       proj_idxs=[1,2],
      9                                                      # axlabel='TIC',
     10                                           )

~/miniconda3/lib/python3.6/site-packages/molpx/visualize.py in FES(MD_trajectories, MD_top, projected_trajectories, proj_idxs, nbins, n_sample, proj_stride, weights, proj_labels, n_overlays, atom_selection, **sample_kwargs)
    217     ax.figure.tight_layout()
    218     axes_wdg.canvas.set_window_title("FES")
--> 219     outbox = _linkutils.MolPXHBox([ngl_wdg, axes_wdg.canvas])
    220     _linkutils.auto_append_these_mpx_attrs(outbox, geoms, ax, _plt.gcf(), ngl_wdg, axes_wdg, data_sample)
    221 

~/miniconda3/lib/python3.6/site-packages/molpx/_linkutils.py in __init__(self, *args, **kwargs)
    204 class MolPXHBox(_HBox, MolPXBox):
    205     def __init__(self, *args, **kwargs):
--> 206         super(MolPXHBox, self).__init__(*args, **kwargs)
    207         self.append_if_existing(args[0])
    208 

~/miniconda3/lib/python3.6/site-packages/ipywidgets/widgets/widget_box.py in __init__(self, children, **kwargs)
     62     def __init__(self, children=(), **kwargs):
     63         kwargs['children'] = children
---> 64         super(Box, self).__init__(**kwargs)
     65         self.on_displayed(Box._fire_children_displayed)
     66 

~/miniconda3/lib/python3.6/site-packages/ipywidgets/widgets/widget.py in __init__(self, **kwargs)
    409         """Public constructor"""
    410         self._model_id = kwargs.pop('model_id', None)
--> 411         super(Widget, self).__init__(**kwargs)
    412 
    413         Widget._call_widget_constructed(self)

~/miniconda3/lib/python3.6/site-packages/traitlets/traitlets.py in __init__(self, *args, **kwargs)
    995             for key, value in kwargs.items():
    996                 if self.has_trait(key):
--> 997                     setattr(self, key, value)
    998                 else:
    999                     # passthrough args that don't set traits to super

~/miniconda3/lib/python3.6/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
    583             raise TraitError('The "%s" trait is read-only.' % self.name)
    584         else:
--> 585             self.set(obj, value)
    586 
    587     def _validate(self, obj, value):

~/miniconda3/lib/python3.6/site-packages/traitlets/traitlets.py in set(self, obj, value)
    557 
    558     def set(self, obj, value):
--> 559         new_value = self._validate(obj, value)
    560         try:
    561             old_value = obj._trait_values[self.name]

~/miniconda3/lib/python3.6/site-packages/traitlets/traitlets.py in _validate(self, obj, value)
    589             return value
    590         if hasattr(self, 'validate'):
--> 591             value = self.validate(obj, value)
    592         if obj._cross_validation_lock is False:
    593             value = self._cross_validate(obj, value)

~/miniconda3/lib/python3.6/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   2240             return value
   2241 
-> 2242         value = self.validate_elements(obj, value)
   2243 
   2244         return value

~/miniconda3/lib/python3.6/site-packages/traitlets/traitlets.py in validate_elements(self, obj, value)
   2252                 v = self._trait._validate(obj, v)
   2253             except TraitError:
-> 2254                 self.element_error(obj, v, self._trait)
   2255             else:
   2256                 validated.append(v)

~/miniconda3/lib/python3.6/site-packages/traitlets/traitlets.py in element_error(self, obj, element, validator)
   2231         e = "Element of the '%s' trait of %s instance must be %s, but a value of %s was specified." \
   2232             % (self.name, class_of(obj), validator.info(), repr_type(element))
-> 2233         raise TraitError(e)
   2234 
   2235     def validate(self, obj, value):

TraitError: Element of the 'children' trait of a MolPXHBox instance must be a Widget, but a value of <matplotlib.backends.backend_agg.FigureCanvasAgg object at 0x7fddb7133898> <class 'matplotlib.backends.backend_agg.FigureCanvasAgg'> was specified.

 
---------------------------------------------------

Can you please help me in resolving this error

with regards
Singam

Thanks for submitting an issue!

Here's a quick checklist of what to include:

- [x] Include a detailed description of the bug or suggestion, optionally with a copy of the output/Exception
- [x] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue).
- [ ] molPX version and operating system versions
- [ ] Minimal example if possible, a Python script, zipped input data (if not too large)

**Comment by marscher** [comment]
please provide the information requested in the check list.

**Comment by marscher** [comment]
hi,

would you please include the list of installed packages (with version 
numbers), as requested in the issue template?

Without it, we can hardly say what this might cause.

use the commands "pip list" or "conda list" and attach the output as a 
file here.

**Comment by marscher** [comment]
@gph82 I get the same exception with a fresh install. Any idea what may be the culprit here? I looks like ipympl may be involved in this.

**Comment by gph82** [comment]
OK, I'll try to take a look myself

**Comment by gokulalgates** [comment]
output of pip list

pip listPackage             Version          
------------------- -----------------
asn1crypto          0.24.0           
backcall            0.1.0            
bhmm                0.6.2            
bleach              2.1.3            
blessings           1.6.1            
blocks              0.2.0            
certifi             2018.1.18        
cffi                1.11.5           
chardet             3.0.4            
conda               4.5.1            
cryptography        2.2.1            
cycler              0.10.0           
Cython              0.27             
decorator           4.2.1            
dill                0.2.7.1          
entrypoints         0.2.3            
freemol             1.158            
fuel                0.2.0            
gpustat             0.4.1            
h5py                2.7.1            
html5lib            1.0.1            
idna                2.6              
ipykernel           4.8.2            
ipympl              0.1.0            
ipython             6.3.0            
ipython-genutils    0.2.0            
ipywidgets          7.2.0            
jedi                0.11.1           
Jinja2              2.10             
joblib              0.11             
jsonschema          2.6.0            
jupyter-client      5.2.3            
jupyter-core        4.4.0            
kiwisolver          1.0.1            
MarkupSafe          1.0              
matplotlib          2.2.2            
mdshare             0.2.1            
mdtraj              1.9.1            
mistune             0.8.3            
mock                2.0.0            
molPX               0.1.7            
msmtools            1.2.1            
multiprocess        0.70.5           
nbconvert           5.3.1            
nbformat            4.4.0            
nglview             1.0              
notebook            5.4.1            
numexpr             2.6.4            
numpy               1.13.3           
nvidia-ml-py3       7.352.0          
olefile             0.45.1           
packaging           17.1             
pandas              0.22.0           
pandocfilters       1.4.1            
ParmEd              0+unknown        
parso               0.1.1            
pathos              0.2.1            
pbr                 4.0.0            
pexpect             4.4.0            
picklable-itertools 0.1.1            
pickleshare         0.7.4            
Pillow              5.1.0            
pip                 10.0.1           
Pmw                 2.0.1            
pox                 0.2.3            
ppft                1.6.4.7.1        
progress-reporter   1.3.1            
progressbar2        3.10.0           
prompt-toolkit      1.0.15           
psutil              5.4.3            
ptyprocess          0.5.2            
pycosat             0.6.3            
pycparser           2.18             
pyEMMA              2.5.2            
Pygments            2.2.0            
pymol               2.0.6            
pyOpenSSL           17.5.0           
pyparsing           2.2.0            
PySocks             1.6.8            
python-dateutil     2.7.2            
python-utils        2.3.0            
pytz                2018.3           
PyYAML              3.11             
pyzmq               17.0.0           
requests            2.18.4           
ruamel-yaml         0.15.35          
scikit-learn        0.19.1           
scipy               1.0.1            
Send2Trash          1.5.0            
setuptools          39.0.1           
simplegeneric       0.8.1            
six                 1.11.0           
tables              3.4.2            
terminado           0.8.1            
testpath            0.3.1            
Theano              1.0.1+70.gd9b8a7c
thermotools         0.2.6            
toolz               0.8.0            
tornado             5.0.1            
tqdm                4.20.0           
traitlets           4.3.2            
urllib3             1.22             
wcwidth             0.1.7            
webencodings        0.5              
wheel               0.31.0           
widgetsnbextension  3.2.0

**Comment by marscher** [comment]
Fixed by #45

**Comment by marscher** [comment]
@gokulalgates you need to set the matplotlib backend to ipympl **before** you import pylab:

``` python
%matplotlib ipympl
from matplotlib import pylab as plt
```
