### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by gph82** [markovmodel/molPX#44]
@marscher any idea? It was a problem with the coverage reporting, I remember we devoted some time to this but got nowhere...

**Comment by marscher** [comment]
On 18.05.2018 20:38, Guillermo Pérez-Hernández wrote:
> @marscher any idea? It was a problem with the coverage reporting, I remember we devoted some time to this but got nowhere...
> 
I think this works now (without branch-coverage, but just line hits,
which is sufficient in my opinion) on a recent branch of mine, will
open up a PR for this soon.
