### ISSUE TITLE
InvalidVersionSpecError: Invalid version spec: =2.7

### ISSUE THREAD

**Issue by streckgumman** [markovmodel/molPX#51]
When trying to install molpx using 

``` conda install -n myenv molpx -c conda-forge ```

 I am met with the message 

``` 
Solving environment: failed

InvalidVersionSpecError: Invalid version spec: =2.7 
```

I also tried opening up a completely new environment in case I had some mismatching dependencies, but that resulted in the same message. I am on Linux, and have conda 4.5.11 and Python 3.6.13 installed. Happy to provide more information if that's needed!

conda info:

``` 
     active environment : linneaenv
    active env location : /home/user/.conda/envs/linneaenv
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : /opt/scp/software/Anaconda3/5.3.0  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/scp/software/Anaconda3/5.3.0/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/.conda/envs
                          /opt/scp/software/Anaconda3/5.3.0/envs
               platform : linux-64
             netrc file : None
           offline mode : False
```

I have had the same problem with other packages, but in that case it was enough to remove the conda-forge channel and add it again, with molpx this didn't work for me.

**Comment by clonker** [comment]
Hi, it seems like your conda version is fairly old, can you try updating it with `conda update -c defaults conda` and then have another go at molpx?

**Comment by streckgumman** [comment]
Thank you for your comment! I can't update conda on my computer, but I tried installing it on another computer with an updated conda and that was no problem. It was probably the older version conda that disturbed somehow.

**Comment by marscher** [comment]
you can have a conda environment with another conda version, or even better mamba.
